travis:
  secure:
    BINSTAR_TOKEN: Lv5GCYYe7xDSwDi0lfWHEgWGUvLRJEcXM/ihUbk+bMVZ+4C+8gdCQ8VKbLfwbU+k8GQ6VkZD6KUmBj2ecP3w0AjvPrcql0DVd6VGsOXR07Zh4F+W7OPICv1+9b0EOvuD/hXrJ9SFGSo+4LUPFZh71YhpqLQQmtp8bcP+rsRYHh635/mcP8CymC9DjMDPcLCj4cSXGcXhOE60gMd7XUghiby+Vy5pp0e+mHqlscNH8e3Q5Np1BKLkEoQM3p3HBcDB88qhMRXnLhZZ23GzjT3ALSg47T7pl/tS1f1/FetqfbDBX6DwXXpHWZ8cWgfUPxW9pprmMXDno6pLcFIase47GfZmklpLlnJcUCf4ep2fzemJaXEcaoFXPvBK3+771+awi/sprHIi6vaBu6EG1oLS+R7Y7eaSQraJC37to3T5bN/OUicqqkqhswqBgy5tYSAhnu1d7uYyDef0Q4u/bs81nIyGf0wjFtsi4PdHqlwgij9nWGdau/LOuWhH7dL86ugyWS/wRYdAbAl0HHIvFN/Q3+IfaoM/Mp3So+UZr0uDdjvt7A1M1xaX9/hWcjvOY3vK1deb3roRx0LnEqWMqZxLi6aR0TjN1ByryhGXpvpZ5qYvqe+xsSwC1M6Po6H9nZcREZVc9mTuG1QKthb6dhAUvDUHd3eqcbqgRCrM+tBfCwg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
