travis:
  secure:
    BINSTAR_TOKEN: U5Z8hi4P/q+gwAem1nnhqWrek3zdFX8mrazymF0GI0xt+NbI1qGqYbbvUabilxL+WywIlQjPGwHHfWPq7Wt/o+pf3Asjd8/Vnu1yqMfJgsJBTD2TnZ0ak4nypYOpXFkvxECB3enQmGyOlRee02QcATKv0jA6VQAb74UR74O/4Q1eAIpGUHsE4ozb94XSOpI6UvewIoiXVwt3GW47nhnzoOyJL2Q+I3anJ++fXbRk/uwVAaznT3R05jPfB5JZqbtAK9s1V7Aa98+3ggVH2BfeXyi42PaxizrSRp/TlH9HOXmGd5FFaI0oLCfUCGFSnBKVr5yAeDmeNwEkFiV2gJBfDVRAkqhEzZRxoVEaK+FvfE7VT+rEVVIgTmeRkjYDZDKIrB2zNDKgeqWbsC9RojZSqjgIxR7utFb+KcjeBiGX/I6oEXIti9GD3ROANdz5HjM87Pqi1lKpchQn5WaACR4Pgal2Q6g5rwzQ4Z/Qb/btrjhPYB+0bTjDtt9JPCvhnSSjCBqAzjPk5t4BWbd+GDUlh09Fow9BMb0+LGyEALHC05gUrYwrq5aqlPgqRoX5CFV+rPdMyVfNA9hryDSiLJVMgA0SZ7wG5NueorRPMzforh62pKC1KdPUKokP9EL9VvuxdxRivqOGQ+TF5xFWkuvuSz/e/sPfsGrv6YwVW9431UM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
