travis:
  secure:
    BINSTAR_TOKEN: ns5whQUe22v/ITRIIQnzKN1Mqrp9/2rTw8TbYEOX8xCDqDwZ0NQNecoJd6686XECsW5HSFMLwLFiV6ZefMGiTTke89K8NdsbrdUeqnieVnrCsud7FUWkcLIXqDNRpWn4ffdaVEgWzKEe3XR3PqKTjhyOt2PRruaGulP1tuMkc9nD2a5lJ7eJjjuOjPKITjcF5SKCVmdHO9QSj8TEDSCqRDbC5NpZHWbiBqARQZjhgp4++F5KsIdygROrqMBklqee8K63BWIBJ02611uD7fKcsd2EzlCpdFCDBA7sPlXhFulA1bVCggPxOwxALhqm2SNxBR1ya8ZjJju9hwsrzNTWtzugscXkVTOFBF1USoWiJa7MkdwUd4rA3oBk02d6n437PImFqyyqjZufxjFD6ESy8bOgn5I6okYfbsuJtz2NbA86dJHns9Y6fPIr0msbUyjSAAi3gd6MOqAvT0/LJXU8LS/tzysnF3Oc7EHCbnMCQV9g5W4IxyEn9WSJUY+5/v0JLFocWY+k18WRTEw3DXJda7IRjCL8WRlZdN5PuwAm02ry5cFbw9y1FF+1XmQPWMcmBzb590BPsVdpoPTsBnYMQLB1dwy3TwmPXE+gJB4bemfP4ZvDYAUvAHQJ51J9X+LROERcFfrYyKS2m5zpXEMZbFgwpkcHXXo88LvsNEag8Qk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
