travis:
  secure:
    BINSTAR_TOKEN: ozjyHs3hD7SlOmC+Awzab6xCpW61HbWeTzitXFdNh4s8gSjlWZnxKgWtGUmRf8lb82zgSir6v5YIRSkfbi2oI1hUOprfkyXPE3M0Ncm8xk3Q6noC8XuzUuNv4IxKVmrxAJbeZdRAVGSHHhiYcI/Yo45c/6EewZySa9CT0YoI4tjrkai2UkfSTIoQDArWUIKRLVvewe4xQpWAtqc+YodViWPfty0yj5fJy27HIJh9T1iEes+1eSvasR5zELdWV7IJ15yJkuxgCmUKF/5OcBb3OJhw05B3i5fxOOb/0XbayB76hNdxtXyhSfDwWFd52jSIjCVoofQ6sy9s38kEzNjCICQC7S0zVv1XwNJHJUbT9glSICAzSCSQDryqR/C+jke0ErJnSDgMeF9+nrAOY/rMMazD0xaUL/dm1WgAwqGRtV3IcMJ4rbpsYB53fSbUa7Eex/7SqYHhBuZg3/YtSDOkvoEcpzppvvmKqxyWajtUoQrg59Vljh5xYpWqLfJwTlbVC+NBdHfUWpJ//tHkhb1uKpT5joJCXpfwd475TfjGN+c7xAILgq76pXfgFmxHDktbxEdAohFQYKyxaiXZzmV28biwXx+MQDY3h/xCRt/CgQ4Mjazo7HwZDp8pNpKVfA53X99QaEs84Gzl7pGDHWniMxrfOJV9V6o07USk8ghz+Ss=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
